financial_analysis_task:
  description: >
    Conduct a comprehensive financial analysis of {stock_name}. Include:
    1. Key financial metrics (P/E ratio, EPS, Revenue growth, etc.)
    2. Balance sheet analysis
    3. Cash flow analysis
    4. Profitability ratios
    5. Debt and leverage analysis
    Make the analysis beginner-friendly while maintaining depth.
  expected_output: >
    A detailed financial analysis report with clear explanations of each metric
    and their implications for investment decisions.
  agent: financial_analyst

investment_recommendation_task:
  description: >
    Based on the financial analysis and market research, provide investment recommendations for {stock_name}.
    Consider:
    1. Current market conditions
    2. Risk factors
    3. Investment timeline
    4. Potential returns
    5. Alternative investment options
    Make recommendations suitable for beginner investors.
  expected_output: >
    A clear investment recommendation with justification, risk assessment, and
    suggested investment strategy tailored for beginner investors.
  agent: investment_advisor

market_research_task:
  description: >
    Research and analyze the market position of {stock_name}, including:
    1. Industry analysis
    2. Competitive landscape
    3. Market trends
    4. Growth opportunities
    5. Potential threats
    Focus on explaining complex market dynamics in simple terms.
  expected_output: >
    A comprehensive market research report highlighting key factors affecting
    the company's market position and future prospects.
  agent: research_analyst

sec_filings_analysis_task:
  description: >
    Review and analyze recent SEC filings for {stock_name}, focusing on:
    1. 10-K and 10-Q reports
    2. Important disclosures
    3. Risk factors
    4. Management discussion
    5. Corporate governance
    Explain findings in beginner-friendly language.
  expected_output: >
    A detailed summary of key findings from SEC filings, highlighting important
    information and potential red flags for investors to consider.
  agent: sec_filings_expert
